name: toolbelt

instance_groups:
  - name: all
    instances: 1
    azs:       [z1]
    vm_type:   default
    stemcell:  default
    networks:
      - name: default
    jobs:
      - { name: toolbelt,            release: toolbelt }
      - { name: toolbelt-everything, release: toolbelt }

  - name: quick
    instances: 1
    azs:       [z1]
    vm_type:   default
    stemcell:  default
    networks:
      - name: default
    jobs:
      - { name: toolbelt,            release: toolbelt }
      - { name: toolbelt-quick,      release: toolbelt }

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
  - alias: default
    os: ubuntu-xenial
    version: latest

releases:
- name:    toolbelt
  version: 3.5.0
  url:     https://github.com/cloudfoundry-community/toolbelt-boshrelease/releases/download/v3.5.0/toolbelt-3.5.0.tgz
  sha1:    08b493f205680323a005ab202e0add186137cec6
